import "~/styles/globals.css";

import { Inter } from "next/font/google";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <nav className="bg-gray-800 p-2">
        <div className="flex justify-between font-semibold text-2xl">
            Gallery
        </div>
        </nav>
    );

}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html>
            <body>
                <TopNav />
                {children}
            </body>
      </html>
  );
}
